[package]
name = "mdbook-jj-example"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi-to-html = "0.2.2"
mdbook = { version = "0.4.44", default-features = false }
pulldown-cmark = "0.12.2"
pulldown-cmark-to-cmark = "20.0.0"
serde_json = "1.0.138"
tempfile = "3.16.0"
